# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eea553823e9f6b4b41f18712e40ee383d7565b490ae0fe46e06afd12b5cf0d99aee18d94a9b837ccf76d3c02b48b2b29d4f962b7e95f07c2143bbbd792da9087

test:
  secret_key_base: 29d593748432671ac832355e18bdf2891c72aab5f54c5222fb6be5c535401648198b8ab9a3391dfe55a185d84426fb774f0c8d216c47004842babc379073e3c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
